version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: llama_chat
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  web:
    image: llama_internet_chatbot_service
    environment:
      - ROCKET_ADDRESS=0.0.0.0
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./models:/app/models
      - logs:/app/logs
    depends_on:
      - db
      - rank_service

  rank_service:
    image: rank_service
    build:
      context: ./rank_service
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  loki:
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - ./promtail-config.yml:/etc/promtail/docker-config.yml
      - logs:/var/log
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - logging

  grafana:
    image: grafana/grafana:master
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - logging

volumes:
  logs:
  grafana-storage:

networks:
  logging: